# Due to the Nix configuration we need to update a hash in test/test.nix when
# npm dependencies change. This workflow runs on dependabot branches, and runs
# a script that makes the necessary update after each dependabot push.
name: Dependabot-post
on:
  push:
    branches:
      - "dependabot/npm_and_yarn/*"

jobs:
  update_npm_deps_hash:
    name: Update NPM dependencies hash
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update Hash
        run: nix run .#update-npm-deps-hash

      - name: Set up Git Config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email '<>'

      # NOTE: Prefixing/appending commit messages with `[dependabot skip]`
      # allows dependabot to rebase/update the pull request, force-pushing
      # over any changes
      - name: Commit changes
        run: |
          git add .
          if [[ $(git status -s) ]]; then
            git commit -m "build(deps): update npm dependencies hash [dependabot skip]" --no-verify
            git push
            echo "Pushed an update to npm dependencies hash"
          else
            echo "Npm dependencies hash was not changed"
          fi
