name: Test & Release
on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  release:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Test
        run: nix develop --command npm test

      - name: Release If Appropriate
        run: nix develop --command npm run semantic-release
