name: Release
on:
  push:
    branches:
      - main
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install Npm Dependencies
        run: nix develop --command npm ci

      - name: Test
        run: nix develop --command npm test

      - name: Release If Appropriate
        run: nix develop --command npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
